Algoritmo "Exemplo1"
//Pergunte um número ao usuário e informe se este número é par ou ímpar

Var
// Seção de Declarações das variáveis
numero: inteiro
resul: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Bem vindo ao programa de Par ou Ìmpar!")
escreva("Escreva um número: ")
leia(numero)

se numero % 2 = 0 entao
    escreva("Seu número é par")
senao
     escreva("Seu número é ímpar")
     
fimse


Fimalgoritmo