Algoritmo "Lista04.2q5"
// Desenvolver um programa que apresente os quadrados dos números inteiros de
// 2 a 50
Var
// Seção de Declarações das variáveis 
num : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
num <- 2
escreval("Aqui abaixo apresentaremos o quadrado dos números de 2 a 50")

enquanto num < 50 faca
         escreval(num * num)
         num <- num + 1
fimenquanto
Fimalgoritmo